### ISSUE TITLE
怎么用？大佬 example调试就报错啊，貌似编辑器不支持模块的语法 ，怎么解决

### ISSUE THREAD

**Issue by dsy525** [plantain-00/js-excel-template#1]
用babel转译下，只能转译一部分，总之就是用不成

**Comment by plantain-00** [comment]
Which environment do you use this in? nodejs or browser?
What's your reproducible code?
What's your error message?

**Comment by dsy525** [comment]
nodejs/webstrom11.0

import JsExcelTemplate from "js-excel-template/nodejs/nodejs";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)

I search for the use of the import, I found my editor does not support。
I use the Babel translation js-excel-template this project，But it seems can only transfer part of the file，

**Comment by plantain-00** [comment]
I believe it's out of scope of this library, you may need a babel plugin like: http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/
Or refer to this question: https://stackoverflow.com/questions/33604470/unexpected-token-import-in-nodejs5-and-babel

**Comment by dsy525** [comment]
I did as you said ，but can‘t run，For a primary noder seems to be difficult to use，only be able to use the module after require。

**Comment by plantain-00** [comment]
You may need this:
```js
const JsExcelTemplate = require("js-excel-template/nodejs/nodejs").default;
const excelTemplate = JsExcelTemplate.fromFile("demo/test.xlsx");
```

http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=JYWwDg9gTgLgBAKQM4FEAeBjApgGwCpbg4CGMWcAZlBCHAEQBWSAtFprs2UaVgPQB2EACZYmA4aKR0A3ACgMEfknhts-QmBJk4AXkSp267mQB0VGgDFgOLAAo6IkBF5llJtDiRo6ASmlA

**Comment by dsy525** [comment]
wow ! wow! it works, Thank you very much dalao, your model very very helpful to me,.thanks again
